export const HOUSE_MEANINGS: Record<number, string> = {
  1: "Eu entro no jogo da vida e tudo recomeca. Essa casa fala de origem, impulso inicial e do tipo de solo emocional em que eu comeco a caminhar.",
  2: "Eu encaro o veu que distorce a realidade e seduz meus sentidos. Aqui eu aprendo a diferenciar intuicao de fantasia, e verdade de narrativa.",
  3: "Eu encontro o fogo que protege e tambem o fogo que destroi. Essa casa pede dominio do impulso: transformar reacao em limite consciente.",
  4: "Eu descubro o desejo de possuir, acumular e garantir controle. A licao e aprender suficiencia: saber quando e construcao e quando e buraco interno.",
  5: "Eu sou chamado a habitar o corpo, a materia e o presente. E o territorio do enraizamento: saude, rotina, limites e prazer com presenca.",
  6: "Eu vejo meus condicionamentos e como me agarro ao conhecido. Essa casa e sobre soltar padroes e permitir que a realidade mude sem eu desmoronar.",
  7: "Eu encaro a relacao com imagem, status e necessidade de aprovacao. A cura aqui e autoestima silenciosa: valor proprio sem inflar ego.",
  8: "Eu confronto comparacao, posse e medo de faltar. Essa casa ensina fluxo: prosperar sem travar a vida por controle.",
  9: "Eu toco o campo do querer, do prazer e da atracao. Aqui eu aprendo a conduzir desejo como forca criativa - nao como vicio.",
  10: "Eu entro na forja onde o excesso e queimado e o essencial permanece. Disciplina aqui nao e punicao: e refinamento para ganhar poder interno.",
  11: "Eu preciso de leveza, beleza e pausa para respirar. O desafio e nao usar prazer como fuga: e alegria que devolve presenca.",
  12: "Eu encontro a ferida da comparacao, quando o brilho do outro me cutuca. Essa casa me chama a transformar inveja em direcao e inspiracao.",
  13: "Eu atravesso um vazio entre fases, onde nada parece acontecer. Aqui eu aprendo que silencio pode ser incubacao - e nao fracasso.",
  14: "Eu desperto para o campo energetico, sensivel e invisivel. A casa pede equilibrio: sentir o sutil sem me dissociar do real.",
  15: "Eu entro no mundo das imagens, simbolos e sonhos que encantam. E criatividade quando consciente - e labirinto quando vira ilusao viciante.",
  16: "Eu encaro repulsa, rejeicao e ciumes como espelhos de feridas. A licao e um nao limpo: limite que protege sem virar odio.",
  17: "Eu sou convidado a acolher com ternura e humanidade. Aqui eu ajudo sem invadir: compaixao com limites, sem salvadorismo.",
  18: "Eu volto ao simples prazer de estar vivo e agradecer. Essa casa limpa a alegria de mascara e devolve celebracao verdadeira.",
  19: "Eu reconheco que cada ato planta uma consequencia. E a casa da responsabilidade: escolher com intencao e assumir os resultados.",
  20: "Eu aprendo a dar sem me esvaziar e sem comprar afeto. Generosidade aqui e fluxo saudavel, nao martirio.",
  21: "Eu ajusto rota e faco reparos internos e externos. A licao e corrigir com humildade, sem viver de culpa.",
  22: "Eu alinjo minha vida a um eixo etico e verdadeiro. Virtude aqui e pratica viva - nao moralismo para julgar.",
  23: "Eu experimento conforto e recompensa, como um ceu aqui na Terra. O alerta e nao estagnar: gratidao sem acomodacao.",
  24: "Eu percebo influencias que desviam meu caminho e minha energia. Essa casa pede discernimento: cortar o que intoxica, sem autoengano.",
  25: "Eu encontro suporte, mentoria e vinculos que elevam. O aprendizado e receber ajuda sem perder autonomia.",
  26: "Eu atravesso dor que amadurece e revela verdade. A casa ensina profundidade - sem me identificar com o papel de vitima.",
  27: "Eu descubro proposito ao servir algo maior do que meu ego. Aqui eu ajudo com sentido, mas sem me anular.",
  28: "Eu desenvolvo fe madura e estabilidade interna. Confianca aqui e firmeza no processo, sem ingenuidade cega.",
  29: "Eu confronto distorcoes do certo e crencas que viram prisao. A licao e questionar e retornar ao que e vivo e real.",
  30: "Eu sinto um impulso de elevacao e melhora. Essa casa pede constancia: subir sem virar perfeccionismo.",
  31: "Eu preciso de refugio para restaurar forcas. O desafio e recolher para curar - nao para fugir da vida.",
  32: "Eu volto ao centro e estabilizo minhas oscilacoes. A casa ensina presenca: serenidade no meio do movimento.",
  33: "Eu aprendo sutileza, refinamento e beleza que vem do ser. O alerta e nao usar charme como mascara ou manipulacao.",
  34: "Eu retorno ao nucleo, ao que e verdadeiro e simples em mim. Essa casa corta excessos e aproxima autenticidade.",
  35: "Eu encaro purga intensa de culpas, medos e sombras. A licao e atravessar o corredor sem fazer dele moradia.",
  36: "Eu ganho visao nitida e mente limpa. Aqui eu aprendo clareza sem obsessao por pureza e controle.",
  37: "Eu acesso sabedoria que ilumina decisoes e caminhos. Essa casa pede integracao: saber que vira vida, nao vaidade mental.",
  38: "Eu sinto o combustivel da existencia circulando em mim. A casa ensina nutricao energetica e respeito ao ritmo (evitar burnout).",
  39: "Eu libero o que intoxica e faco limpeza real. E desapego ativo: soltar sem nojo de mim mesmo.",
  40: "Eu integro partes, conecto pontos e distribuo energia. A licao e coerencia: nao me fragmentar e me dispersar.",
  41: "Eu encontro o sagrado no cotidiano e no simples. Essa casa pede presenca no humano, sem desprezar a vida comum.",
  42: "Eu entro na chama da transmutacao e da coragem. E fogo que transforma - mas pede direcao para nao virar incendio.",
  43: "Eu lembro que estar aqui e uma chance rara. A casa exige responsabilidade: usar o dom da encarnacao com intencao.",
  44: "Eu reconheco pontos cegos e o orgulho de nao querer ver. A cura e humildade: aprender com o real sem negar evidencias.",
  45: "Eu encontro orientacao verdadeira e mapa interno confiavel. Aqui eu organizo visao e caminho sem cair em dogma rigido.",
  46: "Eu separo o essencial do ruido e escolho com precisao. A sombra aparece quando discernimento vira frieza e critica corrosiva.",
  47: "Eu busco serenidade e eixo interno mesmo em turbulencia. E equilibrio vivo: nao e indiferenca, e presenca consciente.",
  48: "Eu assumo acao, coragem e afirmacao do meu caminho. A licao e agir com firmeza sem virar ataque e pressa.",
  49: "Eu ativo acolhimento, intuicao e receptividade. A casa ensina confiar no sentir sem cair em passividade ou dependencia.",
  50: "Eu aprendo forca pela simplicidade e autodomino. O risco e virar dureza e superioridade espiritual.",
  51: "Eu construo base, estrutura e continuidade. Essa casa pede paciencia: sustentar o longo prazo sem estagnar por medo.",
  52: "Eu vejo onde a forca vira dano - em palavra, ato ou intencao. A licao e firmeza protetora sem crueldade e abuso.",
  53: "Eu mergulho nas emocoes e no poder de cura do sentir. A casa pede fluxo: sentir sem me afogar em melodrama.",
  54: "Eu avanco pela repeticao consciente do caminho. Aqui pratica e alquimia diaria - nao ritual mecanico vazio.",
  55: "Eu defino identidade e limites do eu com clareza. A licao e existir sem inflar, sem narcisismo e sem dominacao.",
  56: "Eu volto a vibracao original que organiza tudo por dentro. Essa casa fala de alinhamento profundo, nao de repeticao vazia.",
  57: "Eu aprendo liberdade, leveza e movimento. O desafio e manter o eixo: nao virar instabilidade e fuga.",
  58: "Eu brilho, magnetizo e irradio vitalidade. A casa ensina radiancia com humildade - sem vaidade ou queimar-se.",
  59: "Eu vivo integridade e clareza que cura. A sombra aparece quando eu uso verdade como arma para ferir e endurecer.",
  60: "Eu sustento esperanca pratica e mente favoravel ao caminho. Aqui positividade nao e negacao: e forca lucida.",
  61: "Eu encaro a mente que corroi e envenena tudo. A licao e realismo sem cinismo - lucidez sem rancor.",
  62: "Eu encontro contentamento e suficiencia, sem depender de estimulos. Essa casa ensina paz simples e estavel.",
  63: "Eu reconheco queda de energia e tendencia ao apagamento. A casa pede repouso consciente - para renascer, nao para sumir.",
  64: "Eu retorno a natureza e ao instinto sabio. A licao e harmonizar corpo e mundo, sem brutalidade instintiva cega.",
  65: "Eu entro no silencio profundo onde a verdade aparece. O risco e isolamento que vira prisao e exilio.",
  66: "Eu toco plenitude e extase sereno, como lembranca do sagrado. A sombra e usar isso para fugir do humano e anestesiar dores.",
  67: "Eu recebo a graca feroz que destroi o falso para libertar. Essa casa pede coragem para deixar morrer o que nao serve.",
  68: "Eu experimento expansao e unidade para alem do eu estreito. A licao e integrar isso na vida, sem bypass espiritual.",
  69: "Eu acesso potencia criadora e visao de construcao. Aqui eu crio com humildade - sem complexo de deus e controle absoluto.",
  70: "Eu busco clareza, equilibrio e pureza saudavel. A sombra e moralismo rigido que esteriliza a vida.",
  71: "Eu ativo movimento, ambicao e forca realizadora. A licao e proposito - para nao virar ansiedade e agitacao sem rumo.",
  72: "Eu encaro o apagao, o esquecimento e o fim do ciclo. Essa casa fala de reset: morrer para um modo de ser e recomecar mais consciente.",
};
